/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
const currentDate = new Date()
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('UserData').del()
  await knex('UserData').insert([
    {
      username: 'Budi Susanto',
      password:'Pantai123', 
      email:'BudiSusanto@email.com',
      first_name:'Budi',
      last_name :'Susanto',
      phone_number:'81234567890',
      skilldata_id: 21,
      registered_at: currentDate,
      updated_at: currentDate 
    },
    {
      username: 'Adi Saputra',
      password: 'Kopi2023',
      email: 'AdiSaputra@email.com',
      first_name: 'Adi',
      last_name: 'Saputra',
      phone_number: '82123456789',
      skilldata_id: 22,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Dian Wulandari',
      password: 'Pelan55',
      email: 'DianWulandari@email.com',
      first_name: 'Dian',
      last_name: 'Wulandari',
      phone_number: '81011112222',
      skilldata_id: 23,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Rizky Pratama',
      password: 'Matahari2022',
      email: 'RizkyPratama@email.com',
      first_name: 'Rizky',
      last_name: 'Pratama',
      phone_number: '81555544444',
      skilldata_id: 24,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Ariyanto Setiawan',
      password: 'Jendela99',
      email: 'AriyantoSetiawan@email.com',
      first_name: 'Ariyanto',
      last_name: 'Setiawan',
      phone_number: '8577778888',
      skilldata_id: 27,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Rian Hakim',
      password: 'Motor1234',
      email: 'RianHakim@email.com',
      first_name: 'Rian',
      last_name: 'Hakim',
      phone_number: '81612345678',
      skilldata_id: 28,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Siti Rahmah',
      password: 'Lautan77',
      email: 'SitiRahmah@email.com',
      first_name: 'Siti',
      last_name: 'Rahmah',
      phone_number: '81498765432',
      skilldata_id: 29,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Joko Santoso',
      password: 'Pulau2020',
      email: 'JokoSantoso@email.com',
      first_name: 'Joko',
      last_name: 'Santoso',
      phone_number: '82223456789',
      skilldata_id: 30,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Dwi Suryanto',
      password: 'Bahagia88',
      email: 'DwiSuryanto@email.com',
      first_name: 'Dwi',
      last_name: 'Suryanto',
      phone_number: '81111112222',
      skilldata_id: 31,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Putri Amelia',
      password: 'Ceria12345',
      email: 'PutriAmelia@email.com',
      first_name: 'Putri',
      last_name: 'Amelia',
      phone_number: '85655544444',
      skilldata_id: 32,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Surya Putra',
      password: 'Sungai77',
      email: 'SuryaPutra@email.com',
      first_name: 'Surya',
      last_name: 'Putra',
      phone_number: '8177778888',
      skilldata_id: 33,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Astuti Dewi',
      password: 'Pelangi2022',
      email: 'AstutiDewi@email.com',
      first_name: 'Astuti',
      last_name: 'Dewi',
      phone_number: '81912345678',
      skilldata_id: 34,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Agung Wibowo',
      password: 'Kucing45',
      email: 'AgungWibowo@email.com',
      first_name: 'Agung',
      last_name: 'Wibowo',
      phone_number: '82098765432',
      skilldata_id: 35,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Maya Puspita',
      password: 'Malam123',
      email: 'MayaPuspita@email.com',
      first_name: 'Maya',
      last_name: 'Puspita',
      phone_number: '85123456789',
      skilldata_id: 36,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Agus Mulyono',
      password: 'Hujan567',
      email: 'AgusMulyono@email.com',
      first_name: 'Agus',
      last_name: 'Mulyono',
      phone_number: '81811112222',
      skilldata_id: 37,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Siti Rahayu',
      password: 'Sejuk2021',
      email: 'SitiRahayu@email.com',
      first_name: 'Siti',
      last_name: 'Rahayu',
      phone_number: '85555544444',
      skilldata_id: 38,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Irfan Nugroho',
      password: 'Cerah99',
      email: 'IrfanNugroho@email.com',
      first_name: 'Irfan',
      last_name: 'Nugroho',
      phone_number: '8507778888',
      skilldata_id: 39,
      registered_at: currentDate,
      updated_at: currentDate,
    },
    {
      username: 'Dian Septiawan',
      password: 'Anjing2023',
      email: 'DianSeptiawan@email.com',
      first_name: 'Dian',
      last_name: 'Septiawan',
      phone_number: '82312345678',
      skilldata_id: 40,
      registered_at: currentDate,
      updated_at: currentDate,
    },


  ]);
};
